# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integer_rng <- function(X, base_rng__, pstream__) {
    .Call(`_testStanPackage_integer_rng`, X, base_rng__, pstream__)
}

rcpp_hello_world <- function() {
    .Call(`_testStanPackage_rcpp_hello_world`)
}

